#version 430
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform writeonly image2D outImage;
layout(std140, binding = 1) uniform CameraUBO{
    vec3 camPos;     float _pad0;
    vec3 camRight;   float _pad1;
    vec3 camUp;      float _pad2;
    vec3 camForward; float _pad3;
    float tanHalfFov;
    float aspect;
    bool moving;
    int   _pad4;
} cam;

layout(std140, binding = 3) uniform Objects {
    int numObjects; float objPad0, objPad1, objPad2;
    vec4 objPosRadius[16];
    vec4 objColor[16];
    float  mass[16]; 
} objs;

uniform samplerCube skybox;

const float rs = 1.269e10;
const float D_LAMBDA = 1e7;
const double ESCAPE_R = 1e30;

struct Ray{
    float x, y, z; // Cartesian coordinate
    float r, theta, phi; // Spherical coordinate
    float dr, dtheta, dphi;
    float E, L; // Energy E and angular momentum L 
};

Ray initRay(vec3 pos, vec3 dir){
    Ray ray;

    // 1. Convert cartesian position to spherical coordinate
    ray.x = pos.x;
    ray.y = pos.y;
    ray.z = pos.z;
    ray.r = length(pos);
    ray.theta = acos(pos.z / ray.r);
    ray.phi = atan(pos.y, pos.x);

    // 2. Convert cartesian direction to spherical coordinate
    float dx = dir.x;
    float dy = dir.y;
    float dz = dir.z;

    ray.dr = sin(ray.theta)*cos(ray.phi)*dx + sin(ray.theta)*sin(ray.phi)*dy + cos(ray.theta)*dz;
    ray.dtheta = (cos(ray.theta)*cos(ray.phi)*dx + cos(ray.theta)*sin(ray.phi)*dy - sin(ray.theta)*dz) / ray.r;
    ray.dphi = (-sin(ray.phi)*dx + cos(ray.phi)*dy) / (ray.r * sin(ray.theta));

    // 3. Calculate L and E
    ray.L = ray.r * ray.r * sin(ray.theta) * ray.dphi;
    float f = 1.0 - rs / ray.r;
    float dt_dL = sqrt((ray.dr*ray.dr)/f + ray.r*ray.r*(ray.dtheta*ray.dtheta + sin(ray.theta)*sin(ray.theta)*ray.dphi*ray.dphi));
    ray.E = f * dt_dL;

    return ray;
}

bool intercept(Ray ray, float rs) {
    return ray.r <= rs;
}


void geodesicRHS(Ray ray, out vec3 d1, out vec3 d2) {
    float r = ray.r, theta = ray.theta;
    float dr = ray.dr, dtheta = ray.dtheta, dphi = ray.dphi;
    float f = 1.0 - rs / r;
    float dt_dL = ray.E / f;

    d1 = vec3(dr, dtheta, dphi);
    d2.x = - (rs / (2.0 * r*r)) * f * dt_dL * dt_dL
         + (rs / (2.0 * r*r * f)) * dr * dr
         + r * (dtheta*dtheta + sin(theta)*sin(theta)*dphi*dphi);
    d2.y = -2.0*dr*dtheta/r + sin(theta)*cos(theta)*dphi*dphi;
    d2.z = -2.0*dr*dphi/r - 2.0*cos(theta)/(sin(theta)) * dtheta * dphi;
}

void rk4Step(inout Ray ray, float dL) {
    vec3 k1a, k1b;
    geodesicRHS(ray, k1a, k1b);

    Ray r2 = ray;
    r2.r      += 0.5 * dL * k1a.x;
    r2.theta  += 0.5 * dL * k1a.y;
    r2.phi    += 0.5 * dL * k1a.z;
    r2.dr     += 0.5 * dL * k1b.x;
    r2.dtheta += 0.5 * dL * k1b.y;
    r2.dphi   += 0.5 * dL * k1b.z;

    vec3 k2a, k2b;
    geodesicRHS(r2, k2a, k2b);

    Ray r3 = ray;
    r3.r      += 0.5 * dL * k2a.x;
    r3.theta  += 0.5 * dL * k2a.y;
    r3.phi    += 0.5 * dL * k2a.z;
    r3.dr     += 0.5 * dL * k2b.x;
    r3.dtheta += 0.5 * dL * k2b.y;
    r3.dphi   += 0.5 * dL * k2b.z;

    vec3 k3a, k3b;
    geodesicRHS(r3, k3a, k3b);

    Ray r4 = ray;
    r4.r      += dL * k3a.x;
    r4.theta  += dL * k3a.y;
    r4.phi    += dL * k3a.z;
    r4.dr     += dL * k3b.x;
    r4.dtheta += dL * k3b.y;
    r4.dphi   += dL * k3b.z;

    vec3 k4a, k4b;
    geodesicRHS(r4, k4a, k4b);

    ray.r      += dL * (k1a.x + 2.0 * k2a.x + 2.0 * k3a.x + k4a.x) / 6.0;
    ray.theta  += dL * (k1a.y + 2.0 * k2a.y + 2.0 * k3a.y + k4a.y) / 6.0;
    ray.phi    += dL * (k1a.z + 2.0 * k2a.z + 2.0 * k3a.z + k4a.z) / 6.0;
    ray.dr     += dL * (k1b.x + 2.0 * k2b.x + 2.0 * k3b.x + k4b.x) / 6.0;
    ray.dtheta += dL * (k1b.y + 2.0 * k2b.y + 2.0 * k3b.y + k4b.y) / 6.0;
    ray.dphi   += dL * (k1b.z + 2.0 * k2b.z + 2.0 * k3b.z + k4b.z) / 6.0;

    ray.x = ray.r * sin(ray.theta) * cos(ray.phi);
    ray.y = ray.r * sin(ray.theta) * sin(ray.phi);
    ray.z = ray.r * cos(ray.theta);
}

void main() {
    // Pixel coordinate corresponding to current work item
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy); 

    // Size of output image (pixels)
    ivec2 sz = imageSize(outImage);
    
    int WIDTH = sz.x;
    int HEIGHT = sz.y;

    // Compute Ray direction
    if (pix.x >= sz.x || pix.y >= sz.y) return; // Avoid overflow
    float u = (2 * (pix.x + 0.5) / WIDTH - 1) * // normalize and map pixel coordinate to [-1, 1] (ndc)
                cam.aspect * cam.tanHalfFov;
    float v = (1 - 2 * (pix.y + 0.5) / HEIGHT) * cam.tanHalfFov;
    vec3 dir = normalize(cam.camForward + v * cam.camUp + u * cam.camRight);
    Ray ray = initRay(cam.camPos, dir);

    // Cubemap Sampler
    vec3 dirToSample; // Light escape direction
    vec3 bg;

    vec4 color = vec4(0.0); // background color
    vec3 prevPos = vec3(ray.x, ray.y, ray.z);
    float lambda = 0.0;

    // Check hit event
    bool hitBlackHole = false;
    bool hitDisk = false;
    bool hitObject = false;

    int steps = 6000;

    for (int i = 0; i < steps; ++i) {
        if (intercept(ray, rs)){
            hitBlackHole = true;
            break;
        }
        rk4Step(ray, D_LAMBDA);
        lambda += D_LAMBDA;
        if (ray.r > ESCAPE_R) break;
    }

    dirToSample = normalize(vec3(ray.x, ray.y, ray.z)); // 逃逸方向近似
    bg = texture(skybox, dirToSample).rgb;

    color = hitBlackHole ? vec4(1,0,0,1) : vec4(bg, 1.0);
    imageStore(outImage, pix, color);

}
